//@ui5-bundle sap/ushell/demoapps/ReceiveParametersTestApp/Component-preload.js
sap.ui.require.preload({
	"sap/ushell/demoapps/ReceiveParametersTestApp/Main.controller.js":function(){
// Copyright (c) 2009-2020 SAP SE, All Rights Reserved
(function(){"use strict";sap.ui.controller("sap.ushell.demo.ReceiveParametersTestApp.Main",{getMyComponent:function(){var c=sap.ui.core.Component.getOwnerIdFor(this.getView());var m=sap.ui.component(c);return m;},onInit:function(){},navigate:function(){},isLegalViewName:function(v){return(typeof v==="string")&&(["Detail","View1","View2","View3","View4"].indexOf(v)>=0);},doNavigate:function(){},onExit:function(){jQuery.sap.log.info("sap.ushell.demo.ReceiveParametersTestApp: On Exit of Main.XML.controller called : this.getView().getId():"+this.getView().getId());this.mViewNamesToViews={};if(this.oInnerAppRouter){this.oInnerAppRouter.destroy();}}});}());
},
	"sap/ushell/demoapps/ReceiveParametersTestApp/Main.view.xml":'<core:View xmlns="sap.m" xmlns:core="sap.ui.core" xmlns:layout="sap.ui.layout" xmlns:codeeditor="sap.ui.codeeditor" controllerName="sap.ushell.demo.ReceiveParametersTestApp.Main"><Page showHeader="false"><content><layout:Grid class="sapUiSmallMarginTop" hSpacing="2" defaultSpan="L6 M12 S12"><layout:content><VBox class="sapUiSmallMarginTop"><Title text="Received AppState (JSON.stringified)" titleStyle="H4"/><codeeditor:CodeEditor editable="false" width="40em" height="30em" value="{AppState&gt;/appstate}"/></VBox><Table headerText="Application Startup Parameters" noDataText="No startup parameters passed" items="{startupParameters&gt;/parameters}"><columns><Column width="30%"><Text text="Name"/></Column><Column minScreenWidth="Tablet" demandPopin="true"><Text text="Value"/></Column></columns><items><ColumnListItem><cells><Text text="{startupParameters&gt;key}"/><Text text="{startupParameters&gt;value}"/></cells></ColumnListItem></items></Table></layout:content></layout:Grid></content></Page></core:View>',
	"sap/ushell/demoapps/ReceiveParametersTestApp/manifest.json":'{"_version":"1.1.0","start_url":"start.html","sap.app":{"_version":"1.1.0","i18n":"messagebundle.properties","id":"sap.ushell.demoapps.ReceiveParametersTestApp","type":"component","embeddedBy":"","title":"{{title}}","description":"{{description}}","ach":"CA-UI2-INT-FE","dataSources":{},"cdsViews":[],"offline":true},"sap.ui":{"_version":"1.1.0","technology":"UI5","icons":{"icon":"sap-icon://Fiori5/F0818","favIcon":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/favicon/F0818_KPI_Workspace.ico","phone":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/launchicon/F0818_KPI_Workspace/57_iPhone_Desktop_Launch.png","phone@2":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/launchicon/F0818_KPI_Workspace/114_iPhone-Retina_Web_Clip.png","tablet":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/launchicon/F0818_KPI_Workspace/72_iPad_Desktop_Launch.png","tablet@2":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/launchicon/F0818_KPI_Workspace/144_iPad_Retina_Web_Clip.png","homeScreenIconPhone":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/launchicon/F0818_KPI_Workspace/57_iPhone_Desktop_Launch.png","homeScreenIconPhone@2":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/launchicon/F0818_KPI_Workspace/114_iPhone-Retina_Web_Clip.png","homeScreenIconTablet":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/launchicon/F0818_KPI_Workspace/72_iPad_Desktop_Launch.png","homeScreenIconTablet@2":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/launchicon/F0818_KPI_Workspace/144_iPad_Retina_Web_Clip.png","startupImage320x460":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/splashscreen/320_x_460.png","startupImage640x920":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/splashscreen/640_x_920.png","startupImage640x1096":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/splashscreen/640_x_1096.png","startupImage768x1004":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/splashscreen/768_x_1004.png","startupImage748x1024":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/splashscreen/1024_x_748.png","startupImage1536x2008":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/splashscreen/1536_x_2008.png","startupImage1496x2048":"/sap/public/bc/ui5_ui5/resources/sap/ca/ui/themes/base/img/splashscreen/2048_x_1496.png"},"deviceTypes":{"desktop":true,"tablet":true,"phone":true},"fullWidth":true,"supportedThemes":["sap_hcb","sap_bluecrystal","sap_belize"]},"sap.ui5":{"_version":"1.1.0","resources":{"js":[],"css":[]},"dependencies":{"libs":{"sap.m":{"minVersion":"1.28"}}},"models":{},"rootView":"","handleValidation":false,"config":{},"routing":{},"contentDensities":{"compact":true,"cozy":true}}}',
	"sap/ushell/demoapps/ReceiveParametersTestApp/messagebundle.properties":'#\n#Mon Mar 29 18:19:17 UTC 2021\ndescription=application displaying received parameters of an navigation\ntitle=Application Navigation Parameter display\n',
	"sap/ushell/demoapps/ReceiveParametersTestApp/messagebundle_de.properties":'#\n#Mon Mar 29 18:19:17 UTC 2021\ndescription=Diese Anwendung zeigt die empfangenen Parameter einer App an\ntitle=Appplication Navigation Parameteranzeige\n'
},"sap/ushell/demoapps/ReceiveParametersTestApp/Component-preload"
);
//# sourceMappingURL=Component-preload.js.map