/*!
 * OpenUI5
 * (c) Copyright 2009-2021 SAP SE or an SAP affiliate company.
 * Licensed under the Apache License, Version 2.0 - see LICENSE.txt.
 */
sap.ui.define(["sap/ui/documentation/sdk/controller/BaseController","sap/ui/thirdparty/URI","sap/base/Log","sap/ui/documentation/sdk/controller/util/ResourceDownloadUtil"],function(B,U,L,R){"use strict";var T=sap.ui.require.toUrl("sap/ui/documentation/sdk/tmpl"),M=sap.ui.require.toUrl("sap/ui/demo/mock");return B.extend("sap.ui.documentation.sdk.controller.SampleBaseController",{_aMockFiles:["products.json","supplier.json","img.json"],fetchSourceFile:function(u,t){return R.fetch(u,t).catch(function(e){L.warning(e);return"File not loaded";});},onDownload:function(){sap.ui.require(["sap/ui/thirdparty/jszip","sap/ui/core/util/File"],function(J,F){var z=new J(),r=sap.ui.require.toUrl((this._sId).replace(/\./g,"/")),d=this.oModel.getData(),e=d.includeInDownload||[],h,p=[],a=function(s){var m=[];for(var j=0;j<this._aMockFiles.length;j++){var b=this._aMockFiles[j];if((typeof s==="string")&&s.indexOf(b)>-1){m.push(this._addFileToZip({name:"mockdata/"+b,url:M+"/"+b,formatter:this._formatMockFile},z));}}return Promise.all(m);};for(var i=0;i<d.files.length;i++){var f=d.files[i],u=r+"/"+f.name,c=f.name&&(f.name===d.iframe||f.name.split(".").pop()==="html");p.push(this._addFileToZip({name:f.name,url:u,formatter:c?this._changeIframeBootstrapToCloud:undefined},z));p.push(this.fetchSourceFile(u).then(a.bind(this)));}if(!d.iframe){h=d.files.some(function(f){return f.name==="manifest.json";});p.push(this._addFileToZip({name:"Component.js",url:r+"/"+"Component.js"},z));p.push(this._addFileToZip({name:"index.html",url:T+"/"+(h?"indexevo.html.tmpl":"index.html.tmpl"),formatter:function(I){return this._changeIframeBootstrapToCloud(this._formatIndexHtmlFile(I,d));}.bind(this)},z,true));if(!h){p.push(this._addFileToZip({name:"index.js",url:T+"/"+"index.js.tmpl",formatter:function(I){return this._changeIframeBootstrapToCloud(this._formatIndexJsFile(I,d));}.bind(this)},z,true));}}e.forEach(function(s){p.push(this._addFileToZip({name:s,url:r+"/"+s},z));});
// add generic license file
p.push(this._addFileToZip({name:"LICENSE.txt",url:"LICENSE.txt"},z));Promise.all(p).then(function(){var C=z.generate({type:"blob"});this._openGeneratedFile(C,this._sId);}.bind(this));}.bind(this));},_openGeneratedFile:function(c,i){sap.ui.require(["sap/ui/core/util/File"],function(F){F.save(c,i,"zip","application/zip");});},_addFileToZip:function(f,z,t){var F=f.name,u=f.url,a=f.formatter;return this.fetchSourceFile(u,t).then(function(r){if(r==="File not loaded"){return;
// ignore 404 responses, e.g. for Apache license text file in SAPUI5 environment
}if(a){r=a(r);}z.file(F,r);});},_formatIndexHtmlFile:function(f,d){return f.replace(/{{TITLE}}/g,d.name).replace(/{{SAMPLE_ID}}/g,d.id);},_formatIndexJsFile:function(f,d){return f.replace(/{{TITLE}}/g,d.name).replace(/{{SAMPLE_ID}}/g,d.id).replace(/{{HEIGHT}}/g,d.stretch?'height : "100%", ':"").replace(/{{SCROLLING}}/g,!d.stretch);},_formatMockFile:function(m){var w="test-resources/sap/ui/documentation/sdk/images/",c="https://openui5.hana.ondemand.com/test-resources/sap/ui/documentation/sdk/images/",r=new RegExp(w,"g");return m.replace(r,c);},_changeIframeBootstrapToCloud:function(r){var a=/src=(?:"[^"]*\/sap-ui-core\.js"|'[^']*\/sap-ui-core\.js')/,c=new U(document.baseURI).search(""),o=new U(sap.ui.require.toUrl("")+"/sap-ui-core.js"),b=o.absoluteTo(c).toString();return r.replace(a,'src="'+b+'"');}});});
