//@ui5-bundle sap/ushell/demo/UserDefaults/Component-preload.js
sap.ui.require.preload({
	"sap/ushell/demo/UserDefaults/Component.js":function(){jQuery.sap.declare("sap.ushell.demo.UserDefaults.Component");jQuery.sap.require("sap.ui.core.UIComponent");sap.ui.core.UIComponent.extend("sap.ushell.demo.UserDefaults.Component",{metadata:{manifest:"json"},getAutoPrefixId:function(){return true;},createContent:function(){var m=sap.ui.view({type:sap.ui.core.mvc.ViewType.XML,viewName:"sap.ushell.demo.UserDefaults.view.Main"});return m;},init:function(){sap.ui.core.UIComponent.prototype.init.apply(this,arguments);this.getRouter().initialize();}});
},
	"sap/ushell/demo/UserDefaults/manifest.json":'{"_version":"1.4.0","sap.app":{"_version":"1.1.0","i18n":"messagebundle.properties","id":"sap.ushell.demo.UserDefaults","type":"application","embeddedBy":"","title":"{{title}}","description":"{{description}}","applicationVersion":{"version":"1.1.0"},"ach":"CA-UI2-INT-FE","dataSources":{},"cdsViews":[],"offline":true,"crossNavigation":{"inbounds":{"inb":{"semanticObject":"Action","action":"toUserDefaults","signature":{"parameters":{"GLAccount":{"defaultValue":{"value":"UserDefault.GLAccount","format":"reference"},"filter":{"value":"\\\\d+","format":"regexp"},"required":false},"CostCenter":{"filter":{"value":"UserDefault.CostCenter","format":"reference"},"required":false}},"additionalParameters":"allowed"}}}}},"sap.ui":{"_version":"1.1.0","technology":"UI5","icons":{"icon":"sap-icon://undefined/favorite"},"deviceTypes":{"desktop":true,"tablet":true,"phone":true},"supportedThemes":["sap_hcb","sap_bluecrystal"],"fullWidth":false},"sap.ui5":{"_version":"1.1.0","resources":{"js":[]},"dependencies":{"minUI5Version":"1.28","libs":{"sap.m":{"minVersion":"1.28"}}},"models":{},"rootView":{"viewName":"sap.ushell.demo.UserDefaults.view.Main","type":"XML"},"handleValidation":false,"config":{},"routing":{"config":{"routerClass":"sap.m.routing.Router","viewType":"XML","viewPath":"sap.ushell.demo.UserDefaults.view","controlId":"app","controlAggregation":"detailPages","async":true},"routes":[{"pattern":"SimpleEditor","name":"toEditor","target":"editor"},{"pattern":"UsedParams","name":"toUsedParams","target":"usedParams"},{"pattern":"ShowEvents","name":"toShowEvents","target":"showEvents"}],"targets":{"editor":{"viewName":"SimpleEditor"},"usedParams":{"viewName":"UsedParams"},"showEvents":{"viewName":"ShowEvents"}}},"contentDensities":{"compact":false,"cozy":true}}}',
	"sap/ushell/demo/UserDefaults/messagebundle.properties":'#\n#Mon Mar 29 18:19:17 UTC 2021\ndescription=application for user defaults\ntitle=User Default Application\n',
	"sap/ushell/demo/UserDefaults/view/List.controller.js":function(){
// Copyright (c) 2009-2020 SAP SE, All Rights Reserved
(function(){"use strict";sap.ui.controller("sap.ushell.demo.UserDefaults.view.List",{oApplication:null,onInit:function(){var p=this.oView.getContent()[0],s=sap.ushell.services.AppConfiguration,a,A;if(s){p.setShowFooter(true);a=new sap.m.ActionSheet({placement:sap.m.PlacementType.Top});a.addButton(new sap.ushell.ui.footerbar.JamDiscussButton());a.addButton(new sap.ushell.ui.footerbar.JamShareButton());a.addButton(new sap.ushell.ui.footerbar.AddBookmarkButton());A=new sap.m.Button({press:function(){a.openBy(this);},icon:"sap-icon://action"});p.setFooter(new sap.m.Bar({contentRight:A}));}},getRouter:function(){return this.getOwnerComponent().getRouter();},onViewSelectionChange:function(e){var i=e.getParameter("listItem");var I=(i)?i:oEvt.getSource();if(/editor/.test(I.getId())){this.getRouter().navTo("toEditor");return;}if(/usedParams/.test(I.getId())){this.getRouter().navTo("toUsedParams");return;}if(/showEvents/.test(I.getId())){this.getRouter().navTo("toShowEvents");return;}},});}());
},
	"sap/ushell/demo/UserDefaults/view/List.view.xml":'<core:View xmlns="sap.m" xmlns:core="sap.ui.core" controllerName="sap.ushell.demo.UserDefaults.view.List"><Page><content><List includeItemInSelection="false" mode="SingleSelectMaster" selectionChange="onViewSelectionChange"><items><StandardListItem id="editor" title="Simple Editor" description="Edit available user default values"/><StandardListItem id="usedParams" title="Used Default Parameters" description="Shows defaults used in Target Mappings"/><StandardListItem id="showEvents" title="Show User Default Store Events" description="Shows events"/></items></List></content></Page></core:View>',
	"sap/ushell/demo/UserDefaults/view/Main.controller.js":function(){
/* the subsequent text seems not to contain a copyright or license statement */
sap.ui.controller("sap.ushell.demo.UserDefaults.view.Main",{onInit:function(){var l=sap.ui.view({type:sap.ui.core.mvc.ViewType.XML,viewName:"sap.ushell.demo.UserDefaults.view.List",id:"List"});var e=sap.ui.view({type:sap.ui.core.mvc.ViewType.XML,viewName:"sap.ushell.demo.UserDefaults.view.SimpleEditor",id:"SimpleEditor"});var a=this.byId("app");a.addMasterPage(l);a.addDetailPage(e);},});
},
	"sap/ushell/demo/UserDefaults/view/Main.view.xml":'<View xmlns="sap.m" controllerName="sap.ushell.demo.UserDefaults.view.Main"><SplitApp id="app"><masterPages/><detailPages/></SplitApp></View>',
	"sap/ushell/demo/UserDefaults/view/ShowEvents.controller.js":function(){sap.ui.controller("sap.ushell.demo.UserDefaults.view.ShowEvents",{onInit:function(){"use strict";var t=this;this.oModel=new sap.ui.model.json.JSONModel({aParameterNames:[{name:"InitialParameterName1"}]});this.getView().setModel(this.oModel);if(!sap.ushell.demo.UserDefaults.Component.staticListener){this.registerStaticListener();this.getView().setModel(sap.ushell.demo.UserDefaults.Component.staticListener.getModel(),"storeEvent");}this.handleRefreshParameters();},registerStaticListener:function(){var m=new sap.ui.model.json.JSONModel({count:0,lastEvent:"no event"});sap.ushell.Container.getService("UserDefaultParameters").attachValueStored(function(v){var n=(m.getProperty("/count")||1)+1;m.setProperty("/count",n);var a="name:\""+v.getParameter("parameterName")+"\" new value:"+JSON.stringify(v.getParameter("parameterValue"))+"";m.setProperty("/lastEvent",a);});sap.ushell.demo.UserDefaults.Component.staticListener={getModel:function(){return m;}};},getRouter:function(){"use strict";return this.getOwnerComponent().getRouter();},handleRefreshParameters:function(){var t=this,c=sap.ushell.Container.getService("ClientSideTargetResolution");c.getUserDefaultParameterNames().done(function(p){t.updateParametersForModel(p,t.oModel);});},updateParametersForModel:function(p,m){var P=[];for(i in p){P.push({name:p[i]});}m.setData({"aParameterNames":P},false);}});
},
	"sap/ushell/demo/UserDefaults/view/ShowEvents.view.xml":'<core:View xmlns="sap.m" xmlns:core="sap.ui.core" xmlns:layout="sap.ui.layout" controllerName="sap.ushell.demo.UserDefaults.view.ShowEvents"><Page title="Show User Defaults Parameters Store Events"><content><layout:VerticalLayout><layout:VerticalLayout><MessageStrip class="description" text="This shows the event count and last event of the UserDefaultService" type="Information" showIcon="true"/></layout:VerticalLayout><Text text="{storeEvent&gt;/count}"/><Text text="{storeEvent&gt;/lastEvent}"/></layout:VerticalLayout></content></Page></core:View>',
	"sap/ushell/demo/UserDefaults/view/SimpleEditor.controller.js":function(){
// Copyright (c) 2009-2020 SAP SE, All Rights Reserved
sap.ui.controller("sap.ushell.demo.UserDefaults.view.SimpleEditor",{onInit:function(){"use strict";this.oModel=new sap.ui.model.json.JSONModel({aUserDef:[{"parameterName":"InitialParameterName","valueObject":{"value":"InitialFromApplication"},"editorMetadata":{"displayText":"InitialDisplayTextFromApp","description":"InitialDescriptionFromApp","parameterIndex":"InitialParameterIndex","groupId":"InitialGROUP-IDFromApp","groupTitle":"InitialGroupTitleFromApp"}}]});this.getView().setModel(this.oModel);this.handleRefreshParameters();},getRouter:function(){"use strict";return this.getOwnerComponent().getRouter();},getParameterViaEvent:function(e){var p=e.oSource.getParent().getBindingContext().sPath,P;P=this.oModel.getProperty(p);console.log(P);return P;},handleSaveParameters:function(e){var p=jQuery.extend(true,{},this.getParameterViaEvent(e));if(p.valueObject){if(p.valueObject.extendedValue){p.valueObject.extendedValue=JSON.parse(p.valueObject.extendedValue);}else{delete p.valueObject.extendedValue;}}sap.ushell.Container.getService("UserDefaultParameters").editorSetValue(p.parameterName,p.valueObject);},handleResetParameters:function(e){var t=this,p=this.getParameterViaEvent(e);sap.ushell.Container.getService("UserDefaultParameters").editorSetValue(p.parameterName,{value:undefined}).done(function(){t.handleRefreshParameters();});},handleRefreshParameters:function(){var t=this;sap.ushell.Container.getService("UserDefaultParameters").editorGetParameters().done(function(p){t.updateParametersForModel(p,t.oModel);});},updateParametersForModel:function(p,m){var u=[];for(var P in p){p[P].parameterName=P;if(!p[P].editorMetadata){p[P].editorMetadata={"displayText":p[P].parameterName};}if(p[P].valueObject&&p[P].valueObject.extendedValue){p[P].valueObject.extendedValue=JSON.stringify(p[P].valueObject.extendedValue);}u.push(p[P]);}u.sort(function(d,D){var r=c(d,D);if(r===0){return a(d,D);}return r;});function c(d,D){if(!(D.editorMetadata&&D.editorMetadata.groupId)){return-1;}if(!(d.editorMetadata&&d.editorMetadata.groupId)){return 1;}if(d.editorMetadata.groupId<D.editorMetadata.groupId)return-1;if(d.editorMetadata.groupId>D.editorMetadata.groupId)return 1;return 0;};function a(d,D){if(!(D.editorMetadata&&D.editorMetadata.parameterIndex)){return-1;}if(!(d.editorMetadata&&d.editorMetadata.parameterIndex)){return 1;}return d.editorMetadata.parameterIndex-D.editorMetadata.parameterIndex;};m.setData({"aUserDef":u},false);}});
},
	"sap/ushell/demo/UserDefaults/view/SimpleEditor.view.xml":'<core:View xmlns="sap.m" xmlns:core="sap.ui.core" xmlns:layout="sap.ui.layout" controllerName="sap.ushell.demo.UserDefaults.view.SimpleEditor"><Page title="User Default Parameters"><content><layout:VerticalLayout><layout:VerticalLayout><MessageStrip class="description" text="This is a sample editor allowing you to modify your User Default Parameters. Those are used for intent-based navigation." type="Information" showIcon="true"/><MessageStrip class="description" text="To persist/save the modified parameter value please press enter inside of the input field." type="Information" showIcon="true"/><MessageStrip class="description" text="Note: Only parameters are displayed which are configured in a Target Mapping assigned to a user." type="Warning" showIcon="true"/></layout:VerticalLayout><Button text="Refresh all" class="refreshBtn" press="handleRefreshParameters"/><List items="{path:\'/aUserDef\',sorter:{path:\'editorMetadata/groupId\',descending:false,group:true}}"><InputListItem label="{editorMetadata/displayText}" tooltip="(id: {parameterName}) {editorMetadata/description}"><HBox alignItems="Center" justifyContent="End"><Input id="UserDefaultValue" value="{valueObject/value}" type="Text" change="handleSaveParameters" placeholder="please enter value"/><Input id="ExtendedUserDefaultValue" value="{valueObject/extendedValue}" type="Text" change="handleSaveParameters" placeholder="please enter an extended value"/><Button text="Reset" press="handleResetParameters"/></HBox></InputListItem></List></layout:VerticalLayout></content></Page></core:View>',
	"sap/ushell/demo/UserDefaults/view/UsedParams.controller.js":function(){
/* the subsequent text seems not to contain a copyright or license statement */
sap.ui.controller("sap.ushell.demo.UserDefaults.view.UsedParams",{onInit:function(){"use strict";var t=this;this.oModel=new sap.ui.model.json.JSONModel({aParameterNames:[{name:"InitialParameterName1"}]});this.getView().setModel(this.oModel);this.handleRefreshParameters();},getRouter:function(){"use strict";return this.getOwnerComponent().getRouter();},handleRefreshParameters:function(){var t=this,c=sap.ushell.Container.getService("ClientSideTargetResolution");c.getUserDefaultParameterNames().done(function(p){t.updateParametersForModel(p,t.oModel);});},updateParametersForModel:function(p,m){var P=[];for(i in p){P.push({name:p[i]});}m.setData({"aParameterNames":P},false);}});
},
	"sap/ushell/demo/UserDefaults/view/UsedParams.view.xml":'<core:View xmlns="sap.m" xmlns:core="sap.ui.core" xmlns:layout="sap.ui.layout" controllerName="sap.ushell.demo.UserDefaults.view.UsedParams"><Page title="Assigned User Default Parameters"><content><layout:VerticalLayout><layout:VerticalLayout><MessageStrip class="description" text="This is a list of all User Default Parameters which are configured in Target Mappings assigned to the currently logged on user." type="Information" showIcon="true"/><MessageStrip class="description" text="Note: Each parameter must be handled by a plugin to get its metadata. If that does not happen, no default value or display text is available." type="Warning" showIcon="true"/></layout:VerticalLayout><Button text="Refresh all" class="refreshBtn" press="handleRefreshParameters"/><List items="{/aParameterNames}"><InputListItem label="{name}"/></List></layout:VerticalLayout></content></Page></core:View>'
},"sap/ushell/demo/UserDefaults/Component-preload"
);
//# sourceMappingURL=Component-preload.js.map