//@ui5-bundle sap/ushell/demo/AppPersSample2/Component-preload.js
sap.ui.require.preload({
	"sap/ushell/demo/AppPersSample2/App.controller.js":function(){
// Copyright (c) 2009-2020 SAP SE, All Rights Reserved
jQuery.sap.require("sap.ushell.demo.AppPersSample2.util.TablePersonalizer");sap.ui.controller("sap.ushell.demo.AppPersSample2.App",{onInit:function(){var d,p,D,c,s,C,m,S,t;d={rows:[{cell1:"Cell 1",cell2:"Cell 2",cell3:"Cell 3"},{cell1:"Cell 4",cell2:"Cell 5",cell3:"Cell 6"},{cell1:"Cell 7",cell2:"Cell 8",cell3:"Cell 9"}]};p={container:"sap.ushell.demo.AppPersSample2",item:"mobiletable"};D=new sap.ui.model.json.JSONModel(d);this.getView().setModel(D);m=this.getView().byId("SampleTableMobile");S=this.getView().byId("personalize");c=sap.ushell.Container.getService("Personalization").constants;s={validity:2,keyCategory:c.keyCategory.FIXED_KEY,writeFrequency:c.writeFrequency.LOW,clientStorageAllowed:true};C=sap.ui.core.Component.getOwnerComponentFor(this.getView());t=new sap.ushell.demo.AppPersSample2.util.TablePersonalizer(m,S,p,s,C);}});
},
	"sap/ushell/demo/AppPersSample2/App.view.xml":'<core:View xmlns="sap.m" xmlns:core="sap.ui.core" controllerName="sap.ushell.demo.AppPersSample2.App"><VBox><Panel headerText="Sample Application for Personalization: Case 2: Table"><Table id="SampleTableMobile" headerText="Table header" showSeparators="Inner" items="{/rows}"><headerToolbar><Toolbar><Label text="Test Table for Personalization"/><ToolbarSpacer/><Button id="personalize" icon="sap-icon://table-view"/></Toolbar></headerToolbar><columns><Column id="column1" width="100px"><Label text="Column 1"/></Column><Column id="column2" width="150px"><Label text="Column 2"/></Column><Column id="column3" width="200px"><Label text="Column 3"/></Column></columns><items><ColumnListItem><cells><Text text="{cell1}"/><Text text="{cell2}"/><Text text="{cell3}"/></cells></ColumnListItem></items></Table></Panel></VBox></core:View>',
	"sap/ushell/demo/AppPersSample2/Component.js":function(){jQuery.sap.declare("sap.ushell.demo.AppPersSample2.Component");jQuery.sap.require("sap.ui.core.UIComponent");sap.ui.core.UIComponent.extend("sap.ushell.demo.AppPersSample2.Component",{oMainView:null,metadata:{manifest:"json"},createContent:function(){this.oMainView=sap.ui.xmlview("sap.ushell.demo.AppPersSample2.App");return this.oMainView;}});
},
	"sap/ushell/demo/AppPersSample2/i18n/i18n.properties":'#\n#Mon Mar 29 18:19:17 UTC 2021\nsubtitle=Table Pers\ndescription=Sample app for testing the table personalization\ntitle=App Personalization Sample 2\n',
	"sap/ushell/demo/AppPersSample2/manifest.json":'{"_version":"1.4.0","sap.app":{"_version":"1.1.0","id":"sap.ushell.demo.AppPersSample2","type":"application","i18n":"i18n/i18n.properties","title":"{{title}}","subTitle":"{{subtitle}}","description":"{{description}}","applicationVersion":{"version":"1.1.0"},"ach":"CA-UI2-INT-FE","crossNavigation":{"inbounds":{"inb":{"semanticObject":"Action","action":"toappperssample2","signature":{"parameters":{},"additionalParameters":"allowed"}}}}},"sap.ui":{"_version":"1.1.0","technology":"UI5","icons":{"icon":"sap-icon://provision"},"deviceTypes":{"desktop":true,"tablet":true,"phone":true}},"sap.ui5":{"_version":"1.1.0","dependencies":{"minUI5Version":"1.28","libs":{"sap.m":{"minVersion":"1.28"}}},"contentDensities":{"compact":false,"cozy":true},"services":{"Personalization":{"factoryName":"sap.ushell.ui5service.Personalization"}}}}',
	"sap/ushell/demo/AppPersSample2/util/TablePersonalizer.js":function(){(function(){"use strict";jQuery.sap.declare("sap.ushell.demo.AppPersSample2.util.TablePersonalizer");jQuery.sap.require("sap.ushell.services.Personalization");jQuery.sap.require("sap.m.TablePersoController");sap.ushell.demo.AppPersSample2.util.TablePersonalizer=function(t,s,p,S,c){var P,T;P=sap.ushell.Container.getService("Personalization").getPersonalizer(p,S,c);T=new sap.m.TablePersoController({table:t,persoService:P});T.activate();s.attachPress(function(){T.openDialog();});};}());
}
},"sap/ushell/demo/AppPersSample2/Component-preload"
);
//# sourceMappingURL=Component-preload.js.map